apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: demo
        image: victorpedrota/demo:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
name: demo
labels:
  app: demo
spec:
ports:
  - port: 80
    targetPort: 80
selector:
  app: demo
  tier: demo
type: LoadBalancer
